[phases.setup]
nixPkgs = ["python3", "gcc", "tesseract"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "streamlit run src/app.py --server.port=$PORT --server.address=0.0.0.0"
