[build]
builder = "dockerfile"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environment]
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"
PYTHONUNBUFFERED = "1"
